# version: '3.8'

# services:
#   # 🐰 RabbitMQ
#   rabbitmq:
#     image: rabbitmq:3-management
#     ports:
#       - "5672:5672"
#       - "15672:15672"  # Interfaz web
#     environment:
#       RABBITMQ_DEFAULT_USER: guest
#       RABBITMQ_DEFAULT_PASS: guest

#   # 🛂 Servicio de Usuarios (ej: Laravel o Node)
#   users:
#     image: tu_usuario_dockerhub/users:latest
#     environment:
#       DB_HOST: users_db
#       DB_PORT: 3306
#       DB_DATABASE: users
#       DB_USERNAME: root
#       DB_PASSWORD: root
#     depends_on:
#       - users_db

#   users_db:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: users
#     volumes:
#       - users_data:/var/lib/mysql

#   # 🎤 Servicio de Eventos
#   events:
#     image: tu_usuario_dockerhub/events:latest
#     environment:
#       DB_HOST: events_db
#       DB_PORT: 3306
#       DB_DATABASE: events
#       DB_USERNAME: root
#       DB_PASSWORD: root
#     depends_on:
#       - events_db

#   events_db:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: events
#     volumes:
#       - events_data:/var/lib/mysql

#   # 💳 Servicio de Compras (en Rust, por ejemplo)
#   purchases:
#     image: tu_usuario_dockerhub/purchases:latest
#     environment:
#       DB_HOST: purchases_db
#       DB_PORT: 3306
#       DB_DATABASE: purchases
#       DB_USERNAME: root
#       DB_PASSWORD: root
#       RABBITMQ_HOST: rabbitmq
#       RABBITMQ_PORT: 5672
#       RABBITMQ_USER: guest
#       RABBITMQ_PASS: guest
#       RABBITMQ_QUEUE: notifications_queue
#     depends_on:
#       - purchases_db
#       - rabbitmq

#   purchases_db:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: purchases
#     volumes:
#       - purchases_data:/var/lib/mysql

#   # 📧 Servicio de Notificaciones (Laravel)
#   notifications:
#     image: tu_usuario_dockerhub/notifications:latest
#     environment:
#       RABBITMQ_HOST: rabbitmq
#       RABBITMQ_PORT: 5672
#       RABBITMQ_USER: guest
#       RABBITMQ_PASS: guest
#       RABBITMQ_QUEUE: notifications_queue
#     depends_on:
#       - rabbitmq

#   # 🌐 Frontend (React, Vue, etc.)
#   frontend:
#     image: tu_usuario_dockerhub/frontend:latest
#     depends_on:
#       - users
#       - events
#       - purchases

#   # 🌐 NGINX como Reverse Proxy
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - frontend
#       - users
#       - events
#       - purchases

# volumes:
#   users_data:
#   events_data:
#   purchases_data:
